language: python
python:
  - "3.7"

services:
  - docker

dist: "bionic"
jobs:

install:
  - pip3 install -r dev-requirements.txt
  - pip3 install -r requirements.txt

script:
  - black --check
  - docker-compose build
